"""Add streak to GameHistory

Revision ID: e8039a7889ce
Revises: 
Create Date: 2025-06-27 03:51:04.261119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8039a7889ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_history', schema=None) as batch_op:
        batch_op.drop_column('streak')

    # ### end Alembic commands ###
